"""Notebook-local analysis helpers (kept separate from the root ``utils`` package).

Import as ``notebooks.utils`` after adding the repository root to ``sys.path``.
"""
from __future__ import annotations

from notebooks.utils.io import (
    annotate_result,
    load_cnn_results,
    load_json,
    load_linear_probe_results,
    load_registered_run,
    load_run_args,
    maybe_save_fig,
    maybe_save_table,
    run_metadata,
    safe_filename,
)
from notebooks.utils.labels import (
    COMPARISON_GROUPS,
    ID_COLS,
    MODEL_FAMILY_RULES,
    PER_LABEL_METRICS,
    SUMMARY_METRICS,
    method_label,
    model_family,
    model_label,
)
from notebooks.utils.paths import cnn_run_dir, embedding_timing_md, linear_probe_run_dir, repo_root
from notebooks.utils.plots import (
    plot_best_method_by_dataset,
    plot_cnn_embedding_delta,
    plot_compute_time_vs_performance,
    plot_confusion_matrix,
    plot_model_dataset_heatmap,
    plot_per_class_f1,
    plot_probe_confusion_matrix,
    plot_probe_metrics,
    plot_result_confusion_matrix,
    plot_result_metrics,
    plot_validation_vs_holdout,
    save_all_confusion_matrices,
)
from notebooks.utils.tables import (
    build_cnn_vs_embedding_delta,
    build_cross_dataset_summary,
    build_leaderboard,
    format_seconds,
    get_probe_result,
    get_result,
    load_embedding_timings,
    probe_results_to_frame,
    results_to_frame,
    sorted_probe_results,
    sorted_results,
)
from notebooks.utils.tau_scaling import (
    TAU_DATA_PERCENTAGES,
    TAU_FULL_RUN_NAME,
    load_tau_scaling_results,
    plot_tau_cnn_probe_gap,
    plot_tau_learning_curves,
    plot_tau_per_class_f1,
    tau_cnn_probe_gap,
    tau_scaling_run_name,
)

from notebooks.utils.image_sizes import image_hw

__all__ = [
    "COMPARISON_GROUPS",
    "ID_COLS",
    "MODEL_FAMILY_RULES",
    "PER_LABEL_METRICS",
    "SUMMARY_METRICS",
    "TAU_DATA_PERCENTAGES",
    "TAU_FULL_RUN_NAME",
    "annotate_result",
    "build_cnn_vs_embedding_delta",
    "build_cross_dataset_summary",
    "build_leaderboard",
    "cnn_run_dir",
    "embedding_timing_md",
    "format_seconds",
    "get_probe_result",
    "get_result",
    "linear_probe_run_dir",
    "load_cnn_results",
    "load_embedding_timings",
    "load_json",
    "load_linear_probe_results",
    "load_registered_run",
    "load_run_args",
    "load_tau_scaling_results",
    "maybe_save_fig",
    "maybe_save_table",
    "method_label",
    "model_family",
    "model_label",
    "plot_best_method_by_dataset",
    "plot_cnn_embedding_delta",
    "plot_compute_time_vs_performance",
    "plot_confusion_matrix",
    "plot_model_dataset_heatmap",
    "plot_per_class_f1",
    "plot_probe_confusion_matrix",
    "plot_probe_metrics",
    "plot_result_confusion_matrix",
    "plot_result_metrics",
    "plot_tau_cnn_probe_gap",
    "plot_tau_learning_curves",
    "plot_tau_per_class_f1",
    "plot_validation_vs_holdout",
    "probe_results_to_frame",
    "repo_root",
    "results_to_frame",
    "run_metadata",
    "safe_filename",
    "save_all_confusion_matrices",
    "sorted_probe_results",
    "sorted_results",
    "tau_cnn_probe_gap",
    "tau_scaling_run_name",
    "image_hw",
]
